name: 🐛 Bug Report
description: Report a bug or unexpected behavior in RemObj
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        When I try to use the consume() function with a WebSocket endpoint, I get an error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a provider with '...'
        2. Connect consumer to '...'
        3. Call method '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The remote function should return the result without errors
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: An error is thrown with message "E007"
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        import { provide, consume } from '@remobj/core'
        
        // Your code here
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package(s) are affected?
      multiple: true
      options:
        - "@remobj/core"
        - "@remobj/shared"
        - "@remobj/weakbimap"
        - "@remobj/web"
        - "@remobj/node"
        - "@remobj/devtools"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: RemObj Version
      description: What version of RemObj are you using?
      placeholder: 0.1.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where does this bug occur?
      multiple: true
      options:
        - Node.js
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Deno
        - Bun
        - React Native
        - Electron
        - Other
    validations:
      required: true

  - type: input
    id: environment-version
    attributes:
      label: Environment Version
      description: Version of your runtime/browser
      placeholder: Node.js v20.10.0, Chrome 120
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste any error messages or stack traces
      render: shell
      placeholder: |
        Error: E007
            at remoteCall (core.esm.js:123)
            at Proxy.apply (core.esm.js:456)
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This started happening after upgrading from version X to Y
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have provided all necessary information to reproduce the issue
          required: true
        - label: I am willing to help fix this issue if given guidance
          required: false