name: 🚀 Feature Request
description: Suggest a new feature or enhancement for RemObj
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're facing
      placeholder: |
        Currently, when working with WebRTC connections, there's no built-in way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        It would be great if RemObj could provide a createWebRTCEndpoint() function that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried using the existing WebSocket endpoint, but it doesn't support...
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Provide a concrete example of how you would use this feature
      render: typescript
      placeholder: |
        import { createWebRTCEndpoint } from '@remobj/web'
        
        const endpoint = createWebRTCEndpoint(peerConnection)
        const api = consume<MyAPI>(endpoint)
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Target Package
      description: Which package should this feature be added to?
      options:
        - "@remobj/core"
        - "@remobj/shared"
        - "@remobj/weakbimap"
        - "@remobj/web"
        - "@remobj/node"
        - "@remobj/devtools"
        - New package needed
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Nice to have"
        - "Would improve my workflow"
        - "Important for my use case"
        - "Critical - blocking my project"
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require a breaking change?
      options:
        - "No - fully backward compatible"
        - "Yes - would require breaking changes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references about the feature
      placeholder: |
        This feature is similar to what Comlink does with their transfer() function...
        
        Related issues: #123, #456
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a PR for this feature
          required: false
        - label: I would like guidance on implementing this feature
          required: false
        - label: I can help test this feature
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with RemObj's goals
          required: true